version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
      - ./mongo_config/mongod.conf:/etc/mongo/mongod.conf:ro
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]

  pipeline-etl:
    build: .
    command: python ./src/pipeline_etl.py
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27018/
      - OPENAI_API_KEY=
      - UNSPLASH_API_KEY=
      - UNSPLASH_API_SECRET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SECRET_ACCESS_TOKEN=
      - S3_BUCKET_NAME=

  web:
    build: .
    ports:
      - "80:80"
      - "5768:5768"
    depends_on:
      - pipeline-etl
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27018/
      - OPENAI_API_KEY=
      - UNSPLASH_API_KEY=
      - UNSPLASH_API_SECRET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SECRET_ACCESS_TOKEN=
      - S3_BUCKET_NAME=
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=0

volumes:
  mongo-data:
