name: Deploy react app

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_infrastructure:
    name: Deploy cloudfront and s3 bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Run cloudformation
        id: cloudformation-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: deploy-react-app-infra
          template: deployment/react-app.yaml
          capabilities: CAPABILITY_AUTO_EXPAND
          no-fail-on-empty-changeset: "1"

  build:
    name: Build and upload react app to s3
    runs-on: ubuntu-latest
    needs: deploy_infrastructure
    defaults:
        run:
            working-directory: './frontend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{secrets.AWS_S3_BUCKET}}
          source_dir: './dist'
          destination_dir: ''